version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  projet:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.database=projetSem2
      - spring.data.mongodb.auto-index-creation=true
    depends_on:
      - mongodb
